### ISSUE TITLE
PR Metrics extension 

### ISSUE THREAD

**Issue by Jefinreji19** [microsoft/OMEX-Azure-DevOps-Extensions#20]
We are trying to make use of PR Metrics extension in our builds. However, it is throwing the error “##[error]No agent found in pool On_Premises_Windows which satisfies the specified demands: api-version/6.0, Agent.Version -gtVersion 2.159.2 “

We tried building using on-prem as well as the hosted build agents. 
Extension: https://marketplace.visualstudio.com/items?itemName=ms-omex.prmetrics

Can you please help look into this issue?

**Comment by muiriswoulfe** [comment]
Hi @Jefinreji19. Delighted to hear you're interested in onboarding PR Metrics to your builds.

From looking at the error message, it appears that your build agent `On_Premises_Windows` doesn't meet the baseline requirements for PR Metrics. However, it is likely that we can downgrade some of these requirements. The current requirements are requirements that we knew worked, but we'd be willing to test and release PR Metrics with downgraded requirements if it still works with these lower requirements and if that would help you and others.

I'd like to understand what your requirements would be, so could you navigate to https://dev.azure.com/org/_settings/agentpools (or to the equivalent if you're using an on-premises server), replacing org with the name of your Azure DevOps organization? Select `On_Premises_Windows`, then switch to the Agents tab and click on a random agent name. Within the agent page, click on the Capabilities tab. From this page, could you let me know the version listed for `api-version` and for `Agent.Version`?

By the way, another workaround for now would be to update your build agent to meet those minimum requirements. But this is going to be a more involved solution and we're happy to lessen the requirements from our side if possible.

**Comment by Jefinreji19** [comment]
Hi

The Agent. Version is 2.183.1, and I wasn't able to find the api-version in the capabilities tab. Could you please help us to resolve this issues asap? Can you please see the attached screenshot?

![image](https://user-images.githubusercontent.com/79885490/110576558-98f70d00-8126-11eb-8711-95cd705d65e6.png)

**Comment by muiriswoulfe** [comment]
Thanks for the additional information @Jefinreji19. That very much helps us to narrow down the problem you're seeing.

I'm not 100% sure what API version you have, or what we can reasonably target while still ensuring we don't accidentally break some functionality. However, I believe it should be safe to downgrade from API v6.0 to v4.1. And from looking at the build matrix, it looks like this will cover the vast majority of Azure DevOps versions – Team Foundation Server 2018 U2+ including all versions of Azure DevOps. You can find some information in the API/Software version matrix at <https://docs.microsoft.com/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops> although this just focuses on the major (and not the minor) revisions.

As such, I've created a new PR (linked) to make this downgrade. If you have a way to test this locally, e.g. using the instructions at <https://github.com/microsoft/OMEX-Azure-DevOps-Extensions/tree/main/PipelinesTasks/PRMetricsV1#deploying>, I'd encourage you to try it out and let me know how you get on. Either way, I'll try to get this merged and pushed out to the Marketplace as soon as reasonably possible.

If it doesn't work for you (or you don't believe it will be possible to get it working on your agents), perhaps you can clarify the Azure DevOps version you're using (assuming you're using the on premises and not the cloud version) and I'll see what else we can do.

**Comment by muiriswoulfe** [comment]
@Jefinreji19: I've pushed out v1.0.4 of PR Metrics to the Azure DevOps Marketplace. Your pipeline should be automatically updated to that version. Hope this resolves the issue for you. Keep me posted.

**Comment by Jefinreji19** [comment]
I have Rerun the Pipeline again and I'm getting the following error message:- ##[error]No agent found in pool On_Premises_Windows which satisfies the specified demands: api-version/4.1, Agent.Version -gtVersion 2.159.2
Can you please check and let me know.

**Comment by muiriswoulfe** [comment]
@Jefinreji19 I see you've pulled down the update, as the version requirements specified in your message are the ones from the new version. But it obviously still isn't working for you. Could you tell me which version of Azure DevOps you're using? Every version I've tried it on is working for me, so I need information to narrow down what your environment looks like. Thanks.
